# Generated by Django 5.1.4 on 2024-12-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('set_name', models.CharField(max_length=255)),
                ('language', models.CharField(default='English', max_length=20)),
                ('rarity', models.CharField(max_length=100)),
                ('tcgplayer_price', models.FloatField(blank=True, null=True)),
                ('psa_10_price', models.FloatField(blank=True, null=True)),
                ('price_delta', models.FloatField(blank=True, null=True)),
                ('profit_potential', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
