# Generated by Django 5.1.4 on 2024-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='rarity',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
